export const theme = {
  colors: {
    primary: '#0369a1',
    primaryDark: '#0c4a6e',
    primaryLight: '#0ea5e9',
    accent: '#0c4a6e',
    background: '#f8fafc',
    surface: '#ffffff',
    card: '#ffffff',
    text: '#0f172a',
    textSecondary: '#64748b',
    textTertiary: '#94a3b8',
    border: '#e2e8f0',
    error: '#dc2626',
    errorDark: '#b91c1c',
    success: '#16a34a',
    successDark: '#15803d',
    warning: '#ea580c',
    warningDark: '#c2410c',
    info: '#0284c7',
    disabled: '#cbd5e1',
    placeholder: '#94a3b8',
    // Status colors
    statusActive: '#10b981',
    statusCompleted: '#6366f1',
    statusOnHold: '#f59e0b',
    statusDraft: '#94a3b8',
    statusPaid: '#10b981',
    statusOverdue: '#dc2626',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 18,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  },
  fontWeight: {
    normal: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
  },
};

export type Theme = typeof theme;
