import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ClientBreakdown {
  clientName: string
  hours: number
  entries: number
  amount: number
  avgRate: number
}

interface ReportData {
  startDate: string
  endDate: string
  totalEarnings: number
  totalHours: number
  totalEntries: number
  clientBreakdown: ClientBreakdown[]
}

/**
 * Generate a PDF report for time entries
 */
export function generatePDFReport(data: ReportData, userPlan: 'free' | 'pro' = 'free'): void {
  const doc = new jsPDF()

  // Set font
  doc.setFont('helvetica')

  // Add header
  doc.setFontSize(24)
  doc.setTextColor(15, 23, 42) // slate-950
  doc.text('TradeTimer Report', 20, 25)

  // Add period information
  doc.setFontSize(11)
  doc.setTextColor(71, 85, 105) // slate-600
  doc.text(`Period: ${data.startDate} to ${data.endDate}`, 20, 35)
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 41)

  // Add horizontal line
  doc.setDrawColor(226, 232, 240) // slate-200
  doc.setLineWidth(0.5)
  doc.line(20, 47, 190, 47)

  // Summary section
  doc.setFontSize(14)
  doc.setTextColor(15, 23, 42)
  doc.text('Summary', 20, 57)

  doc.setFontSize(11)
  doc.setTextColor(71, 85, 105)

  const summaryY = 67
  const summaryLineHeight = 7

  doc.text('Total Earnings:', 25, summaryY)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text(`$${data.totalEarnings.toFixed(2)}`, 70, summaryY)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(71, 85, 105)
  doc.text('Total Hours:', 25, summaryY + summaryLineHeight)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text(data.totalHours.toFixed(1), 70, summaryY + summaryLineHeight)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(71, 85, 105)
  doc.text('Total Entries:', 25, summaryY + summaryLineHeight * 2)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text(data.totalEntries.toString(), 70, summaryY + summaryLineHeight * 2)

  // Client breakdown table
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(14)
  doc.setTextColor(15, 23, 42)
  doc.text('Client Breakdown', 20, 95)

  // Prepare table data
  const tableData = data.clientBreakdown.map((client) => [
    client.clientName,
    client.hours.toFixed(1),
    client.entries.toString(),
    `$${client.avgRate.toFixed(2)}`,
    `$${client.amount.toFixed(2)}`,
  ])

  // Generate table
  autoTable(doc, {
    startY: 102,
    head: [['Client', 'Hours', 'Entries', 'Avg Rate', 'Amount']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [241, 245, 249], // slate-100
      textColor: [15, 23, 42], // slate-950
      fontStyle: 'bold',
      fontSize: 10,
      halign: 'left',
    },
    bodyStyles: {
      textColor: [51, 65, 85], // slate-700
      fontSize: 9,
    },
    columnStyles: {
      0: { cellWidth: 60 }, // Client
      1: { cellWidth: 25, halign: 'right', font: 'courier' }, // Hours
      2: { cellWidth: 25, halign: 'right' }, // Entries
      3: { cellWidth: 30, halign: 'right', font: 'courier' }, // Avg Rate
      4: { cellWidth: 35, halign: 'right', font: 'courier' }, // Amount
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // slate-50
    },
  })

  // Add footer
  const pageCount = doc.getNumberOfPages()
  const pageHeight = doc.internal.pageSize.height

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(9)
    doc.setTextColor(148, 163, 184) // slate-400
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width / 2,
      pageHeight - 10,
      { align: 'center' }
    )

    if (userPlan === 'free') {
      // Add branding for free tier users
      doc.setFontSize(9)
      doc.setTextColor(100, 100, 100)
      doc.text(
        'Generated with TradeTimer - Upgrade to Pro to remove this message',
        doc.internal.pageSize.width / 2,
        pageHeight - 5,
        { align: 'center' }
      )
    } else {
      // Clean footer for Pro users
      doc.text(
        'Generated by TradeTimer',
        doc.internal.pageSize.width / 2,
        pageHeight - 5,
        { align: 'center' }
      )
    }
  }

  // Generate filename
  const filename = `TradeTimer-Report-${new Date().toISOString().split('T')[0]}.pdf`

  // Save the PDF
  doc.save(filename)
}

/**
 * Format date for display in PDF
 */
export function formatDateForPDF(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
}

/**
 * Generate invoice PDF
 */
export async function generateInvoicePDF(invoiceData: any, userPlan: 'free' | 'pro' = 'free'): Promise<void> {
  const doc = new jsPDF()

  // Set font
  doc.setFont('helvetica')

  // Add header
  doc.setFontSize(24)
  doc.setTextColor(15, 23, 42)
  doc.text('INVOICE', 20, 25)

  // Invoice number and date
  doc.setFontSize(11)
  doc.setTextColor(71, 85, 105)
  doc.text(`Invoice #: ${invoiceData.invoice_number}`, 20, 35)
  doc.text(`Date: ${formatDateForPDF(invoiceData.created_at)}`, 20, 41)
  if (invoiceData.due_date) {
    doc.text(`Due Date: ${formatDateForPDF(invoiceData.due_date)}`, 20, 47)
  }

  // Client information
  doc.setFontSize(14)
  doc.setTextColor(15, 23, 42)
  doc.text('Bill To:', 20, 62)

  doc.setFontSize(11)
  doc.setTextColor(71, 85, 105)
  doc.text(invoiceData.client_name, 20, 70)

  // Line items table
  const tableData = (invoiceData.line_items || []).map((item: any) => [
    item.description || '',
    item.quantity?.toString() || '1',
    `$${item.rate?.toFixed(2) || '0.00'}`,
    `$${item.amount?.toFixed(2) || '0.00'}`,
  ])

  autoTable(doc, {
    startY: 85,
    head: [['Description', 'Quantity', 'Rate', 'Amount']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [241, 245, 249],
      textColor: [15, 23, 42],
      fontStyle: 'bold',
      fontSize: 10,
      halign: 'left',
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 9,
    },
    columnStyles: {
      0: { cellWidth: 90 },
      1: { cellWidth: 25, halign: 'right' },
      2: { cellWidth: 35, halign: 'right', font: 'courier' },
      3: { cellWidth: 35, halign: 'right', font: 'courier' },
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  })

  // Total
  const finalY = (doc as any).lastAutoTable.finalY || 85
  doc.setFontSize(14)
  doc.setTextColor(15, 23, 42)
  doc.setFont('helvetica', 'bold')
  doc.text(`Total: $${invoiceData.total_amount?.toFixed(2) || '0.00'}`, 190, finalY + 15, { align: 'right' })

  // Add footer with branding based on plan
  const pageHeight = doc.internal.pageSize.height

  if (userPlan === 'free') {
    doc.setFontSize(9)
    doc.setTextColor(100, 100, 100)
    doc.text(
      'Generated with TradeTimer - Upgrade to Pro to remove this message',
      doc.internal.pageSize.width / 2,
      pageHeight - 10,
      { align: 'center' }
    )
  }

  // Save the PDF
  const filename = `Invoice-${invoiceData.invoice_number}.pdf`
  doc.save(filename)
}
