import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Section,
  Text,
  Hr,
} from '@react-email/components'

interface WeeklySummaryEmailProps {
  userName: string
  weekStart: string
  weekEnd: string
  totalHours: number
  totalEarnings: number
  topClient: string
  topClientHours: number
}

export default function WeeklySummaryEmail({
  userName = 'User',
  weekStart = '2025-01-27',
  weekEnd = '2025-02-02',
  totalHours = 40,
  totalEarnings = 2000,
  topClient = 'Client A',
  topClientHours = 20,
}: WeeklySummaryEmailProps) {
  const formattedEarnings = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(totalEarnings)

  const weekStartFormatted = new Date(weekStart).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  })

  const weekEndFormatted = new Date(weekEnd).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })

  return (
    <Html>
      <Head />
      <Preview>Your weekly time tracking summary</Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>Weekly Summary</Heading>

          <Text style={text}>Hi {userName},</Text>

          <Text style={text}>
            Here is your time tracking summary for the week of {weekStartFormatted} - {weekEndFormatted}.
          </Text>

          <Section style={statsBox}>
            <div style={statItem}>
              <Text style={statLabel}>Total Hours</Text>
              <Text style={statValue}>{totalHours.toFixed(1)}</Text>
            </div>

            <div style={statItem}>
              <Text style={statLabel}>Total Earnings</Text>
              <Text style={statValue}>{formattedEarnings}</Text>
            </div>

            <div style={statItem}>
              <Text style={statLabel}>Top Client</Text>
              <Text style={statValue}>{topClient}</Text>
              <Text style={statSubtext}>{topClientHours.toFixed(1)} hours</Text>
            </div>
          </Section>

          <Text style={text}>
            Keep up the great work! Log in to TradeTimer to view detailed reports and generate invoices.
          </Text>

          <Hr style={hr} />

          <Text style={footer}>
            This summary was generated by TradeTimer.
            To unsubscribe from weekly summaries, update your email preferences in settings.
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

const main = {
  backgroundColor: '#f6f9fc',
  fontFamily:
    '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
}

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
}

const h1 = {
  color: '#0369a1',
  fontSize: '32px',
  fontWeight: 'bold',
  margin: '40px 0',
  padding: '0 48px',
}

const text = {
  color: '#333',
  fontSize: '16px',
  lineHeight: '26px',
  margin: '16px 0',
  padding: '0 48px',
}

const statsBox = {
  backgroundColor: '#f0f9ff',
  borderRadius: '8px',
  margin: '32px 48px',
  padding: '24px',
  display: 'flex',
  flexDirection: 'column' as const,
  gap: '20px',
}

const statItem = {
  textAlign: 'center' as const,
}

const statLabel = {
  color: '#64748b',
  fontSize: '14px',
  fontWeight: '500',
  margin: '0 0 8px 0',
}

const statValue = {
  color: '#0369a1',
  fontSize: '32px',
  fontWeight: 'bold',
  margin: '0',
}

const statSubtext = {
  color: '#64748b',
  fontSize: '14px',
  margin: '4px 0 0 0',
}

const hr = {
  borderColor: '#e6ebf1',
  margin: '32px 0',
}

const footer = {
  color: '#8898aa',
  fontSize: '12px',
  lineHeight: '16px',
  padding: '0 48px',
}
